In [41]:
import numpy as np

In [6]:
a = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([a] *100)
print(nz)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4

In [11]:
b = np.array([[1,2,3],[4,6,7],[8,9,10],[9,8,7]])
print(b.shape)
print(b)

(4, 3)
[[ 1  2  3]
 [ 4  6  7]
 [ 8  9 10]
 [ 9  8  7]]


In [47]:
r1 = np.random.randint(-5,3,(4,3))


print(a)

[[-60 -60  15 -60 -75   0 -45 -75  30 -45 -60  45  15 -30  15  30]
 [-30  30  60  30 -75 -60 -30 -75 -45 -75  45  30 -45 -15 -75   0]
 [ 30  15  60  15 -30 -45  45  30  15 -75   0 -45  15 -15 -60  60]
 [ 60 -30  60 -75  30   0  60  15 -75  30 -60  15  60   0 -45   0]
 [ 45  60   0 -30  15 -15 -60 -75  15  15 -30 -45 -30 -30  45   0]
 [ 30   0   0  30 -30  60 -45 -30 -15  45 -15  15 -60  15 -15 -45]
 [ 30 -45  15 -60  60 -45 -30 -45  15 -60 -60  60   0  15  15  30]
 [ 45   0 -60 -75  30 -30  15 -30  45   0 -45  15 -60  15  45 -30]
 [-60  60 -75 -30  15  15 -75   0 -60 -60 -60 -45 -60  60 -45  30]
 [  0 -45   0 -60 -60 -15 -45  30 -45  60  15  45  60 -75  60   0]]


In [35]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])