In [1]:
import numpy as np


In [3]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*100)
print(z)
print(nz)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0

In [4]:
b = np.array([[1,2,3],[4,6,7],[8,9,10]])
print(b.shape)

(3, 3)


In [6]:
a = [0,1,2,3,4,5,6,7,8,9,10]
b = np.array([a]*10)
print(b)
print(b.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]
(10, 11)


In [10]:
r1 = np.random.randint(-5,6,(5,5))
print(r1)

[[-5  1 -3 -4  3]
 [ 2 -5  0 -4 -1]
 [ 5  1 -3 -2 -1]
 [ 2 -4  5  3  0]
 [-3  0  1 -5  1]]


In [11]:
#start , stop , gap
np.arange(0,50, .5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [12]:
#start, stop number of item
np.linspace(0,50 , 100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

array attribites
- shape
- dtype
- ndim
- size
basic operation
- sum
- mean 
- min
- max
- std
- reshape
- transpose
- flatten

In [ ]:
x = np.random.rand(3,3)

In [13]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean())
print(a.max())
print(a.std())
print(a.var())
# all the methods  can be used with axis


4.045663464127647
[0.85294365 1.45076117 1.74195864]
[2.34783343 1.69783003]


In [18]:
z = np.random.randint(11,99, (5,5))
print(z)
print(z.transpose())
print('flattened')

[[51 13 67 29 51]
 [43 15 76 16 74]
 [64 20 33 76 53]
 [83 44 86 77 74]
 [76 90 45 31 14]]
[[51 43 64 83 76]
 [13 15 20 44 90]
 [67 76 33 86 45]
 [29 16 76 77 31]
 [51 74 53 74 14]]
flattened


In [19]:
a =([[2,7],[8,9]])
b = ([[2,5],[6,9]])
print(a)
print(b)

[[2, 7], [8, 9]]
[[2, 5], [6, 9]]


In [ ]:
print(a + b) 
print(a - b)
print(7 / b)
print(a * b)
print(a @ b)
print(a.dot(b))


In [38]:
a[0]

[2, 7]

In [51]:
a = [1,2,3,4,5]
b = np.array([a]*5)
print(b)


TypeError: 'list' object is not callable